/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.View;

import Presentacion.Controller.detailIngresoController;
import Presentacion.Model.billeteraModel;
import javax.swing.JLabel;

/**
 *
 * @author Administrador
 */
public class detailIngreso extends javax.swing.JFrame {

    private final billeteraModel modelo;
    
    private detailIngresoController control;
    
    /**
     * Creates new form detailIngreso
     */
    public detailIngreso(billeteraModel b) {
        modelo = b;
        initComponents();
        capturarEventos();
    }
    
     public billeteraModel getModelo() {
        return modelo;
    }
    
    public detailIngresoController getControl() {
         if(control == null){
            control = new detailIngresoController(this);
        }
        return control;
    }

    public JLabel getLblcategoriamostrar() {
        return lblcategoriamostrar;
    }

    public JLabel getLblcuentamostrar() {
        return lblcuentamostrar;
    }

    public JLabel getLbldetallemostrar() {
        return lbldetallemostrar;
    }

    public JLabel getLblfechamostrar() {
        return lblfechamostrar;
    }

    public JLabel getLblvalormostrar() {
        return lblvalormostrar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblcuenta = new javax.swing.JLabel();
        lblcategoria = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        lbldetalle = new javax.swing.JLabel();
        lblfechamostrar = new javax.swing.JLabel();
        lblcuentamostrar = new javax.swing.JLabel();
        lblcategoriamostrar = new javax.swing.JLabel();
        lblvalormostrar = new javax.swing.JLabel();
        lbldetallemostrar = new javax.swing.JLabel();
        btnatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setText("Detalle Ingreso:");

        lblfecha.setText("Fecha:");

        lblcuenta.setText("Cuenta:");

        lblcategoria.setText("Categoria:");

        lblvalor.setText("Valor:");

        lbldetalle.setText("Detalle:");

        btnatras.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldetalle)
                    .addComponent(lblvalor)
                    .addComponent(lblcategoria)
                    .addComponent(lblcuenta)
                    .addComponent(lbltitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblfecha)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcuentamostrar)
                            .addComponent(lblfechamostrar)
                            .addComponent(lblcategoriamostrar)
                            .addComponent(lblvalormostrar)
                            .addComponent(lbldetallemostrar))))
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnatras)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbltitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfecha)
                    .addComponent(lblfechamostrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcuenta)
                    .addComponent(lblcuentamostrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcategoria)
                    .addComponent(lblcategoriamostrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvalor)
                    .addComponent(lblvalormostrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldetalle)
                    .addComponent(lbldetallemostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnatras)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblcategoriamostrar;
    private javax.swing.JLabel lblcuenta;
    private javax.swing.JLabel lblcuentamostrar;
    private javax.swing.JLabel lbldetalle;
    private javax.swing.JLabel lbldetallemostrar;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfechamostrar;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JLabel lblvalormostrar;
    // End of variables declaration//GEN-END:variables

    private void capturarEventos(){
       btnatras.addActionListener(getControl());
    }
            
 }
