/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.View;

import Presentacion.Controller.detailCuentasController;
import Presentacion.Model.billeteraModel;
import javax.swing.JList;

/**
 *
 * @author Estudiantes
 */
public class detailCount extends javax.swing.JFrame {

   private final billeteraModel modelo;
    private detailCuentasController control;
    /**
     * Creates new form addCuenta
     */
    public detailCount(billeteraModel b) {
          modelo = b;  
        initComponents();
        capturarEventos();
    }
    
  


    public billeteraModel getModelo() {
        return modelo;
    }

    public detailCuentasController getControl() {
                if(control == null){
            control = new detailCuentasController(this);
        }
        return control;
    }

    public JList<String> getLstCuentas() {
        return lstCuentas;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresoTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCuentas = new javax.swing.JList<>();
        btnatrascta = new javax.swing.JButton();
        btnagregarcta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIngresoTitulo.setText("Cuentas");

        lstCuentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCuentas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCuentasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCuentas);

        btnatrascta.setText("Atras");

        btnagregarcta.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnatrascta)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIngresoTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnagregarcta))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblIngresoTitulo)
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnagregarcta)
                            .addGap(18, 18, 18)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63)
                    .addComponent(btnatrascta)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCuentasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCuentasValueChanged
        System.out.println("metodoVista 1");
        getControl().selectItem();
      
    }//GEN-LAST:event_lstCuentasValueChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarcta;
    private javax.swing.JButton btnatrascta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIngresoTitulo;
    private javax.swing.JList<String> lstCuentas;
    // End of variables declaration//GEN-END:variables


    private void capturarEventos() {
      btnagregarcta.addActionListener(getControl());      
      btnatrascta.addActionListener(getControl());      
    }


}
