/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.View;

import Presentacion.Controller.gastoController;
import Presentacion.Model.billeteraModel;
import javax.swing.JList;

/**
 *
 * @author Administrador
 */
public class gasto extends javax.swing.JFrame {

    private final billeteraModel modelo;
    
    private gastoController control;
    
    /**
     * Creates new form ingreso
     */
    public JList<String> getLstgastos() {
        return lstgastos;
    }

    public gasto(billeteraModel b) {
        modelo = b;
        initComponents();
        capturarEventos();
    }
    
    public billeteraModel getModelo() {
        return modelo;
    }
    
    public gastoController getControl() {
         if(control == null){
            control = new gastoController(this);
        }
        return control;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblgastos = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstgastos = new javax.swing.JList<>();
        btnatras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblgastos.setText("Gastos");

        btnagregar.setText("Agregar");

        lstgastos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstgastos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstgastosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstgastos);

        btnatras.setText("Atras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnatras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblgastos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnagregar)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnagregar)
                    .addComponent(lblgastos))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnatras)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstgastosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstgastosValueChanged
        getControl().selectItem();
    }//GEN-LAST:event_lstgastosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnatras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblgastos;
    private javax.swing.JList<String> lstgastos;
    // End of variables declaration//GEN-END:variables
    
    private void capturarEventos() {
        btnagregar.addActionListener(getControl());   
        btnatras.addActionListener(getControl());   
    }


}
