/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion.View;

import Presentacion.Controller.ingresoController;
import Presentacion.Model.billeteraModel;
import javax.swing.JLabel;
import javax.swing.JList;

/**
 *
 * @author Briam
 */
public class ingreso extends javax.swing.JFrame {

    public void setLstIngresos(JList<String> lstIngresos) {
        this.lstIngresos = lstIngresos;
    }

    public JLabel getLblError() {
        return lblError;
    }

    public JLabel getLblFechaActual() {
        return lblFechaActual;
    }

    public JList<String> getLstIngresos() {
        return lstIngresos;
    }

    private final billeteraModel modelo;
    private ingresoController control;
    
    /**
     * Creates new form ingreso
     */
    public ingreso(billeteraModel b) {
        modelo = b;
        initComponents();
        capturarEventos();
    }
    
    public billeteraModel getModelo() {
        return modelo;
    }
    
    public ingresoController getControl() {
         if(control == null){
            control = new ingresoController(this);
        }
        return control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresoTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstIngresos = new javax.swing.JList<>();
        lblFechaActual = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIngresoTitulo.setText("Ingresos");

        lstIngresos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstIngresos);
        lstIngresos.getAccessibleContext().setAccessibleName("lstIngresos");

        btnagregar.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError)
                    .addComponent(lblFechaActual)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblIngresoTitulo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnagregar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngresoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechaActual)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnagregar)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblError)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        lblIngresoTitulo.getAccessibleContext().setAccessibleName("lblIngresoTitulo");
        lblFechaActual.getAccessibleContext().setAccessibleName("lblFechaActual");
        lblError.getAccessibleContext().setAccessibleName("lblError");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblIngresoTitulo;
    private javax.swing.JList<String> lstIngresos;
    // End of variables declaration//GEN-END:variables

    private void capturarEventos() {
      btnagregar.addActionListener(getControl());
    }

}
